### PR TITLE
Fix error in parsing XSD types; handle attributes on all elements; more correctly handle nullability in XSDs

### LINKED ISSUE #474: XSD types not parsed correctly in some cased in XSDToSchema + XSD attributes ignored in some cases

### PR DESCRIPTION
**Pull request by srowen**
Closes #474 

- Fixes how QNames were looked up from the schema - did not actually work before
- Attributes were not handled in most cases; now they are
- Nullability wasn't handled correctly in many cases according to minOccurs; now should be
- Refactored test code to share schema construction code

### CODE REVIEW

File: src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala [hunk 1]
```diff
@@ -121,64 +121,73 @@ object XSDToSchema {
             content.getContent match {
               case extension: XmlSchemaSimpleContentExtension =>
                 val baseStructField = getStructField(xmlSchema,
-                  xmlSchema.getTypeByName(extension.getBaseTypeName))
+                  xmlSchema.getParent.getTypeByQName(extension.getBaseTypeName))
```
Comment (srowen) [inline src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala:124]: This fixes the lookup; xmlSchema has no built in types to lookup but the parent collection does.

File: src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala [hunk 2]
```diff
@@ -121,64 +121,73 @@ object XSDToSchema {
...
-                      field
+                      StructField(element.getName, baseStructField.dataType, nullable)
                     } else {
-                      StructField(element.getName, ArrayType(field.dataType))
+                      StructField(element.getName, ArrayType(baseStructField.dataType), nullable)
                     }
                   }
-                StructField(complexType.getName, StructType(fields))
+              }
+            val attributes = complexType.getAttributes.asScala.map {
```
Comment (srowen) [inline src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala:179]: This adds attribute handling on other element types

File: src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala [hunk 3]
```diff
@@ -121,64 +121,73 @@ object XSDToSchema {
...
+                      } else {
+                        StructField(element.getName, ArrayType(baseStructField.dataType), nullable)
+                      }
+                  }
+                // xs:choice
+                case choice: XmlSchemaChoice =>
+                  choice.getItems.asScala.map { case element: XmlSchemaElement =>
                     val baseStructField = getStructField(xmlSchema, element.getSchemaType)
-                    val field = StructField(element.getName, baseStructField.dataType)
+                    val nullable = element.getMinOccurs == 0
```
Comment (srowen) [inline src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala:154]: Several fixes like this to account for min occurs in deciding nullability.

File: src/test/scala/com/databricks/spark/xml/TestUtils.scala [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.databricks.spark.xml
+
+import org.apache.spark.sql.types.{ArrayType, DataType, StringType, StructField, StructType}
+
+private[xml] object TestUtils {
```
Comment (srowen) [inline src/test/scala/com/databricks/spark/xml/TestUtils.scala:19]: Pulled this code out to share the schema construction utilities.

**Review by srowen — COMMENTED** [review]
CC @seddonm1 in case you're interested.
CC @miku872 too
